version: '3'

services:
  web:
    container_name: agenda_php
    build: .
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html

  db:
    container_name: agenda_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - '3306:3306'
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: my_phpmyadmin
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      - PMA_HOST=db
    ports:
      - '8081:80'

volumes:
  dbdata:
